Fix missing render contex targ
The context param is a mandatory arg to render(). Causes PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Twig\Template::render(), 0 passed in ... if omitted.